env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the xdroid-CAF-builder repo

task:
    name: xdroid-CAF # Project name
    timeout_in: 3h
    container:
        image: dopaemon/bionic:latest
        cpu: 8
        memory: 32G
    sync_script: # To sync source
      - ./sync # Source sync script
    build_script: # Actual build script foreground
      - ./build # Build script to run
