env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[unl3ivf0ghk8pus5tg6i2insh3j61hqrnvftho6d0qv235lac5hl5l21hd4pue8j6phs1c1ec0naqi9uq0smm227ht23b9fctirjef]"
    bot_api: "ENCRYPTED[flluak6lnp4of8qn9v7ujcr4gsqjc325ashqeh7bv3t5iuhk0usu0scli1lqj2p8mvc08m55op8q33c70ntnruapt8en20obm180gs]"
    tg_id: "ENCRYPTED[2ght25q6fs4sg83r9eb4egu5rd2dnt50rorlr5n2qotuta9c2ih8vn66eqo1kjpnq0gojv6dkkjoc37nl9i2kloj0vpeme5r3j7op8v]"
task:
    name: xdroid-CAF
    timeout_in: 120m
    container:
      image: inok2341/builder:latest
      cpu: 8
      memory: 32G      

    rclone_setup_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
    download_ccache_background_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Download ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
      - df -h && free -h && nproc && cat /etc/os* && env
      - curl https://transfer.sh/get/1cLYAsL/ccache.tar.gz -o /tmp/ccache.tar.gz
      - cd /tmp
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
    sync_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Sync ROM at $(date)&chat_id=${tg_id}&parse_mode=html"
      - git config --global  user.name "ramadhannangga"
      - git config --global  user.email "ramadhananggayudhanto@gmail.com"
      - mkdir -p /tmp/rom # Where to sync source
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/xdroid-CAF/xd_manifest -b eleven -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone --depth=1 https://github.com/ramadhannangga/device_asus_X01BD --single-branch device/asus/X01BD
      - git clone --depth=1 https://github.com/ramadhannangga/device_asus_sdm660-common --single-branch device/asus/sdm660-common
      - git clone --depth=1 https://github.com/ramadhannangga/vendor_asus --single-branch vendor/asus
      - git clone --depth=1 https://github.com/ramadhannangga/msm-4.4 --single-branch kernel/asus/sdm660
    monitor_background_script:
      - ./monitor
    build_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Build ROM at $(date)&chat_id=${tg_id}&parse_mode=html"
      - ./build
      - time rclone copy /tmp/rom/out/error.log inok: -P
    upload_rom_script:
      - ./uprom
    compress_ccache_script:    
      - ./tarccache
    upload_ccache_script:
      - cd /tmp
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Uploading ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
      - time rclone copy ccache.tar.gz inok:nusantara -P 
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Upload ccache done at $(date)&chat_id=${tg_id}&parse_mode=html"
