#!/bin/bash
cd /tmp/rom # Depends on where source got synced

# Normal build steps
. build/envsetup.sh
lunch aosp_olivewood-userdebug
export USE_CCACHE=1
ccache -M 20G # It took only 6.4GB for mido

mka bacon

curl --upload-file ./out/target/product/olivewood/*.zip  https://transfer.sh/ppui.zip