#!/bin/bash
sudo apt install wget
sudo apt install python2 -y
mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
git config --global user.name "ramadhannangga"
git config --global user.email "ramadhananggayudhanto@gmail.com"
export KBUILD_BUILD_USER=ramadhannangga
export KBUILD_BUILD_HOST=irisprjkt

# Make a directory where Repo will be stored and add it to the path
mkdir ~/.bin
PATH=~/.bin:$PATH

# Download Repo itself
curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo

# Make Repo executable
chmod a+x ~/.bin/repo

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo init -u https://github.com/xdroid-CAF/xd_manifest -b eleven  --depth=1
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

# Cloning DeviceTree, VendorTree, KernelTree
git clone https://github.com/ramadhannangga/device_asus_X01BD --depth=1 device/asus/X01BD
git clone https://github.com/ramadhannangga/device_asus_sdm660-common --depth=1 device/asus/sdm660-common
git clone https://github.com/ramadhannangga/vendor_asus --depth=1 vendor/asus
git clone https://github.com/ThankYouMario/proprietary_vendor_qcom_sdclang.git -b ruby-12 --depth=1 prebuilts/clang/host/linux-x86/clang-sdllvm
git clone https://github.com/ramadhannangga/msm-4.4 --depth=1 kernel/asus/sdm660
rm -rf vendor/qcom/common
git clone https://github.com/P-404/proprietary_vendor_qcom_common --depth=1 vendor/qcom/common
rm -rf device/qcom/common
git clone https://github.com/P-404/android_device_qcom_common --depth=1 device/qcom/common
rm -rf prebuilts/clang/host/linux-x86/clang-xRageTC
git clone https://github.com/ramadhannangga/iRISxe-Clang --depth=1 prebuilts/clang/host/linux-x86/clang-iRISxeTC