name: Build & upload toolchain
on:
  push:
    branches:
      - master
  schedule:
    # 3 PM PST on Saturdays
    - cron: '0 22 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download scripts
        uses: actions/checkout@v2

      - name: Deploy builder
        run: |
          bash sync
          bash build
